codes/All_Input_types.html
I have made a HTML file that represents all the input types present in our HTML , so that any third person can try how they works
=> This html file represents all the inputs types present in HTML

codes/index.html
=> added index.html

codes/all_list_styling_types.html
=> Added "All list styling types" in html

codes/analog_cum_digital_clock.html
Please accept my pull request 🙂
[Please subscribe to my youtube channel](https://youtube.com/c/spacify18)
=> Made analog_cum_digital_clock.html

codes/loremipsum_generator.html
💬 Here is a phrase generator for Hacktoberfest projects 😄
=> Lorem Ipsum Generator

codes/code_editor.html
💻 Here's a little code editor 😃
=> Code Editor

codes/pomodore_timer.html
⏰ Another of the indispensable these days of PR's 😄
=> Pomodoro Timer

codes/snake_game.html
=> Snake game

codes/Web_Accessible_Alternatives.html
Added an HTML file to /codes dir showcasing some semantic HTML elements to use instead of div tags.
=> Add accessibility alternatives to div tags

TicketCounter.html
=> Ticket counter web page

codes/html_editor.html
Add HTML Editor Project Capable of rendering html Strings with the help of an Iframe.
=> Add HTML Editor Project

codes/Stylish contactform.html
Added new contact form , Hope u like it and accept my PR. For any quires u can comment to this post
=> added new contact form

codes/Calculator.html
My simple and awesome style :)
=> Add header and css in calculator

codes/roll-a-die.html
Small code which gives you the ability to roll a die giving a random number between 1-6.
=> roll-a-die.html added

codes/stylish-cards.html
added html file called stylish-cards
=> added html file called stylish-cards

codes/Firebase-Feedback.html
1. It's A Simple Feedback Form.
2. It Uses Firebase to Store all its feedback
3. You can get your Credentials from Firebase Console.
=> Firebase-Feedback

codes/personal website
=> personal website

codes/Golf-Club-Membership.html
Hello,
I have made a Membership form for Golf club using HTML and bit of CSS. Kindly review this file and accept my PR.
Thank you :)
=> Golf-club-membership.html

codes/Weather Card New Delhi.html
I've made a simple weather card that displays the basic weather information at New Delhi, India on a daily basis using [`Open-Meteo` 's](https://open-meteo.com/en) open-source weather API
=> Weather Card for New Delhi

codes/drum_kit.html
Kindly accept my code for Hacktoberfest 2021
Thankyou
@AnushkaSamarasinghe
=> drum kit code added

codes/item-list.html
I have added an item-list.html file into the codes section. Item-list.html file is a responsive webpage to add lists. It contains a very good and cool interface. 
a screen-shot of this page:------>
=> item-list.html file added

codes/age-calculator/index.html, codes/age-calculator/script.js, codes/age-calculator/style.css
please merge this under hacktoberfest 2021 tag
=> age-calculator

codes/Sachin-Tendulkar-Tribute-Page/index.html, codes/Sachin-Tendulkar-Tribute-Page/style.css
Added Sachin Tendulkar's Tribute page.
=> Added Sachin Tendulkar tribute page

codes/random password.html
I added one file Random Password Generator.
=> Random Password Generator

codes/Stylish_glowingbuttons.html
=> Added glowing buttons

codes/Cal_Shrijan/index.html, codes/Cal_Shrijan/index.js, codes/Cal_Shrijan/styles.css
This is my simple calculator made using HTML, CSS & JavaScript.
=> Added a Simple Calculator

codes/BMI_Cal_Bushra/index.html, codes/BMI_Cal_Bushra/script.js, codes/BMI_Cal_Bushra/style.css
This is a simple BMI Calculator made with HTML CSS and JavaScript .
=> Added a bmi calculator

codes/bmicalculator/index.html, codes/bmicalculator/script.js, codes/bmicalculator/style.css
=> added body mass index (BMI) calc

codes/glowing text css.html
=> added new html file

codes/Simple-Game/CSS.css, codes/Simple-Game/index.html
=> Simple Animation

codes/stone paper scissor/stone_paper_scissor.html
Made a stone paper scissor game using html,css,javascript
=> stone_paper_scissor.html

codes/to do list/INDEX.HTML
to do list web app using html,css,bootstrap,javascript
=> to do list web app

codes/Online_Meals/index.html, codes/Online_Meals/style.css
I have created a **frontend webpage**.
Please review the pull request and merge in main branch.
Thanks!!
=> created online_meals_website

codes/Digital Clock/index.html
Can you please verify this under Hacktoberfest 21?
=> Digital Clock file added

codes/randomNoGenerator.html
It contains HTML, inline-CSS, and embedded javascript. It generated a number of the random number given as input.
=> Random Number Generator

codes/After Graduation Exams Info
A page where information of exams after Engineering possible
=> Create After Graduation Exams Info

codes/A-Survey-Form-Page/index.html, codes/A-Survey-Form-Page/style.css
I've made this simple survey form page, please check my PR, i appreciate.
=> Adding a survey form page

codes/Admission Form.html
Project of admission form using html, css, javascript.
=> Admission Form.html

codes/Intro_Page/tathastu_intro_Page.html
simple_tathastu intro page is added
=> tathastu_intro_page is added

codes/surveyform.html
survey form using pure html hope you appreciate it
=>  survey form using pure html

codes/Login Forms/AnimatedLogin.html
I created animated login using html and css. please have a look at once. It is very awesome.
=> I create animated login

codes/Login-Signup page(2 in one)/index.html, codes/Login-Signup page(2 in one)/style.css
please add my work to your repository.
=> My Login and signup in one page

codes/SurveyForm/Styles.css, codes/SurveyForm/index.html
=> Added Survey Form

codes/A-Technical-Documentation-Page/index.html, codes/A-Technical-Documentation-Page/style.css
I've made this Technical Documentation Page, Kindly review  my PR, Thank you.
=> Adding A Technical Documentation Page

Flappy box.html
A fun , informative PR based on the implementations of HTML and JavaScript .
Description :
A fun game based on the mechanics and methods of Flappy bird .
Trying to make way through the obstacles by pressing the "FLAP" button properly !!
@AnushkaSamarasinghe hope that u will verify and accept this as a Repository for Hacktoberfest 2021 !!
Made By https://github.com/Anirudha10
=> Create Flappy box.html

codes/Flappy Cube/Flappycube.html
Flappy Cube small game like flappy bird game in HTML
=> Add Flappy Cube game

codes/Tic-tac-toe/ttt.css, codes/Tic-tac-toe/ttt.html, codes/Tic-tac-toe/ttt.js
Hey there,
I have added simple tic-tac-toe game.
=> simple js game

codes/Gradient Background/index.html, codes/Gradient Background/style.css
added HTML and CSS code to generate gradient background for webpages
=> Added Gradient Background for webpages in code

codes/navigation.html
i recently learned html and css and created a navigation panel using div and alignment ,styles.
=> navigation.html

codes/Technical-Documentation-Page/index.html, codes/Technical-Documentation-Page/style.css
Please accept this PR. It is a technical documentation page for JavaScript made by me (Addison Hardley).
Thanks!
=> JavaScript Documentation Page by Addison Hardley

codes/calculator-html&js/app.js, codes/calculator-html&js/index.html
calculator app using html and js.
=> calculator app using html and js

codes/footer.css, codes/footer.html
A footer section for a website.
=> Footer Section

codes/a/index.html
=> Tapush HTML Color Change File

Binary search
Make a binary search algorithm in cpp #hactoberfest2021
=> Binarysearch.cpp
